<template>
  <div>
    <b-container class="bv-example-row">
      <b-row>
        <b-col>
          <div>
            <b-jumbotron
              header="Overview"
              lead="Listing battery charching, solar production and consumption details"
            >
              <!-- <p>For more information visit website</p> -->
              <!-- <b-button variant="primary" href="#">More Info</b-button> -->
              <b-list-group>
                <b-list-group-item variant="primary">Battery Charging 100%</b-list-group-item>
                <b-list-group-item variant="success">Solar Production 1.6kW</b-list-group-item>
                <b-list-group-item variant="success">Consumption 540W</b-list-group-item>
              </b-list-group>
            </b-jumbotron>
          </div>
        </b-col>
      </b-row>
      <b-row>
        <b-col>
          <b-card
            overlay
            img-src="http://www2.macs.hw.ac.uk/~sl106/data/1.jpg"
            img-alt="Card Image"
            text-variant="black"
            title
            sub-title
          >
            <h1>Solar Production</h1>
            <h4>Total energy generated by the solar pannels</h4>
          </b-card>
        </b-col>
      </b-row>
    </b-container>
  </div>
</template>

<script>
export default {}
</script>

<style></style>
